<?php

namespace App\Exports;

use Illuminate\Support\Collection;
use Maatwebsite\Excel\Concerns\FromCollection;
use Maatwebsite\Excel\Concerns\WithHeadings;
use Maatwebsite\Excel\Concerns\WithEvents;
use Maatwebsite\Excel\Events\AfterSheet;
use PhpOffice\PhpSpreadsheet\Style\Alignment;
use PhpOffice\PhpSpreadsheet\Style\Font;

class CGSRenewalReportExport implements FromCollection, WithHeadings, WithEvents
{
    protected $cooperatives;
    protected $user;

    public function __construct(Collection $cooperatives, $user)
    {
        $this->cooperatives = $cooperatives;
        $this->user = $user;
    }

    public function collection()
    {
        return $this->cooperatives;
    }

    public function headings(): array
    {
        return [
            'CDA Registration No',
            'Transport Cooperative Name',
            'Validity Date',
            'Accreditation No',
            'Region',
        ];
    }

    public function registerEvents(): array
    {
        return [
            AfterSheet::class => function (AfterSheet $event) {
                $sheet = $event->sheet;

                // Insert title and user info
                $sheet->insertNewRowBefore(1, 5);

                $sheet->mergeCells('A1:E1');
                $sheet->setCellValue('A1', 'CGS Renewal Report');
                $sheet->getStyle('A1')->applyFromArray([
                    'font' => ['bold' => true, 'size' => 14],
                    'alignment' => ['horizontal' => Alignment::HORIZONTAL_CENTER],
                ]);

                $sheet->mergeCells('A2:E2');
                $sheet->setCellValue('A2', 'Generated on: ' . now()->format('F j, Y'));

                $sheet->mergeCells('A3:E3');
                $sheet->setCellValue('A3', 'Generated by: ' . $this->user->employee_id_no . ' - ' . $this->user->firstname . ' ' . $this->user->lastname);

                $sheet->mergeCells('A4:E4');
                $sheet->setCellValue('A4', 'Division: ' . $this->user->division . ' | Role: ' . $this->user->role . ' | Email: ' . $this->user->email);

                $sheet->getStyle('A2:A4')->applyFromArray([
                    'font' => ['italic' => true, 'size' => 10],
                ]);

                // Style header row
                $sheet->getStyle('A6:E6')->applyFromArray([
                    'font' => ['bold' => true],
                    'fill' => [
                        'fillType' => 'solid',
                        'startColor' => ['rgb' => 'f2f2f2'],
                    ],
                    'alignment' => [
                        'horizontal' => Alignment::HORIZONTAL_LEFT,
                    ],
                    'borders' => [
                        'allBorders' => [
                            'borderStyle' => \PhpOffice\PhpSpreadsheet\Style\Border::BORDER_THIN,
                        ],
                    ],
                ]);
            },
        ];
    }
}
