<table>
    <thead>
        <tr>
            <th colspan="7" style="font-size: 18px; font-weight: bold; text-align: center; background-color: #c0c9d9;">
                @if(request('report_type') === 'acc_app')
                    Accreditation Applications
                @elseif(request('report_type') === 'cgs_app')
                    CGS Renewal Applications
                @else
                    Application Report
                @endif
            </th>
        </tr>
        <tr>
            <th colspan="7" style="text-align: center;">
                Generated on: {{ now()->format('d M Y') }}
            </th>
        </tr>
        <tr>
            <th>#</th>
            <th>Cooperative Name</th>
            <th>CDA Registration No.</th>
            <th>Registration Date</th>
            <th>Region</th>
            <th>Status</th>
            <th>Submitted On</th>
        </tr>
    </thead>
    <tbody>
        @forelse ($cooperatives as $index => $coop)
            <tr>
                <td>{{ $index + 1 }}</td>
                <td>{{ $coop->tc_name }}</td>
                <td>{{ $coop->cda_reg_no }}</td>
                <td>{{ $coop->cda_reg_date ? \Carbon\Carbon::parse($coop->cda_reg_date)->format('d M Y') : 'N/A' }}</td>
                <td>{{ $coop->region }}</td>
                <td>{{ ucfirst($coop->status) }}</td>
                <td>{{ \Carbon\Carbon::parse($coop->created_at)->format('d M Y') }}</td>
            </tr>
        @empty
            <tr>
                <td colspan="7" style="text-align: center;">No data available.</td>
            </tr>
        @endforelse

        <tr><td colspan="7"></td></tr> <!-- Spacer Row -->

        <tr>
            <td colspan="7" style="font-weight: bold;">Report Generated By</td>
        </tr>
        <tr>
            <td colspan="7">
                <strong>Employee ID No:</strong> {{ $user->employee_id_no }}<br>
                <strong>Name:</strong> {{ $user->firstname }} {{ $user->lastname }}<br>
                <strong>Division:</strong> {{ $user->division }}<br>
                <strong>Role:</strong> {{ $user->role }}<br>
                <strong>Email:</strong> {{ $user->email }}
            </td>
        </tr>
    </tbody>
</table>
