@php
    use Carbon\Carbon;

    $regionNames = [
        '010000000' => 'Region I (Ilocos Region)',
        '020000000' => 'Region II (Cagayan Valley)',
        '030000000' => 'Region III (Central Luzon)',
        '040000000' => 'Region IV-A (CALABARZON)',
        '170000000' => 'MIMAROPA Region',
        '050000000' => 'Region V (Bicol Region)',
        '060000000' => 'Region VI (Western Visayas)',
        '070000000' => 'Region VII (Central Visayas)',
        '080000000' => 'Region VIII (Eastern Visayas)',
        '090000000' => 'Region IX (Zamboanga Peninsula)',
        '100000000' => 'Region X (Northern Mindanao)',
        '110000000' => 'Region XI (Davao Region)',
        '120000000' => 'Region XII (SOCCSKSARGEN)',
        '130000000' => 'Region XIII (Caraga)',
        'CAR' => 'Cordillera Administrative Region',
        'NCR' => 'National Capital Region',
        'BARMM' => 'Bangsamoro Autonomous Region in Muslim Mindanao',
    ];
@endphp

<table>
    <thead>
        <tr><th colspan="7" style="font-size: 16px; font-weight: bold; text-align: center;">Application Report</th></tr>
        <tr><th colspan="7" style="font-size: 10px;">Generated on: {{ Carbon::now()->format('F j, Y') }}</th></tr>
        <tr><th colspan="7" style="font-size: 10px;">Generated by: {{ $user->employee_id_no }} - {{ $user->firstname }} {{ $user->lastname }}</th></tr>
        <tr><th colspan="7" style="font-size: 10px;">Division: {{ $user->division }} | Role: {{ $user->role }} | Email: {{ $user->email }}</th></tr>
        <tr><td colspan="7"></td></tr> {{-- Spacer Row --}}
        <tr style="background-color: #f2f2f2; font-weight: bold; text-align: center;">
            <th>#</th>
            <th>Cooperative Name</th>
            <th>CDA Registration No.</th>
            <th>Registration Date</th>
            <th>Region</th>
            <th>Status</th>
            <th>Submitted On</th>
        </tr>
    </thead>
    <tbody>
        @foreach ($cooperatives as $index => $coop)
            <tr>
                <td>{{ $index + 1 }}</td>
                <td>{{ $coop->tc_name }}</td>
                <td>{{ $coop->cda_reg_no }}</td>
                <td>{{ $coop->cda_reg_date ? Carbon::parse($coop->cda_reg_date)->format('d M Y') : 'N/A' }}</td>
                <td>{{ $regionNames[$coop->region] ?? $coop->region }}</td>
                <td>{{ ucfirst($coop->status) }}</td>
                <td>{{ Carbon::parse($coop->created_at)->format('d M Y') }}</td>
            </tr>
        @endforeach
    </tbody>
</table>
