<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>CGS Renewal Report</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            font-size: 12px;
        }

        .table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
        }

        .table th,
        .table td {
            padding: 8px;
            text-align: left;
            border: 1px solid #e5e7eb;
        }

        .table th {
            background-color: #c0c9d9;
            font-weight: bold;
        }

        .table tr:hover {
            background-color: #f9fafb;
        }

        .header {
            text-align: center;
            padding-top: 20px;
            font-size: 24px;
            font-weight: 600;
            color: #4b5563;
        }

        .subheader {
            text-align: center;
            color: #6b7280;
            font-size: 12px;
            margin-top: 5px;
        }

        .no-records {
            text-align: center;
            font-size: 16px;
            color: #ef4444;
        }

        .user-info {
            margin-top: 40px;
            padding-top: 20px;
            border-top: 1px solid #e5e7eb;
        }

        .user-info h3 {
            font-size: 16px;
            font-weight: 600;
            color: #374151;
        }

        .user-info p {
            font-size: 14px;
            color: #6b7280;
        }

        .logo-container {
            text-align: center;
            margin-bottom: 20px;
        }

        .logo {
            max-width: 100%;
            height: auto;
        }
    </style>
</head>

<body>
    @php
        $path = public_path('images/OTC-UpdatedBannerLogo4Black.png');
        $type = pathinfo($path, PATHINFO_EXTENSION);
        $data = file_get_contents($path);
        $base64 = 'data:image/' . $type . ';base64,' . base64_encode($data);
    @endphp
    <div class="logo-container">
        <img src="{{ $base64 }}" alt="OTC Banner Logo" class="logo">
    </div>
    <div class="header">
        <h2>CGS Renewal Report</h2>
        <p class="subheader">Generated on: {{ now()->format('F j, Y') }}</p>
    </div>

    <div class="max-w-7xl mx-auto px-6 py-4">
        @if ($cooperatives->isEmpty())
            <div class="no-records">
                <p>No records found</p>
            </div>
        @else
            <table class="table">
                <thead>
                    <tr>
                        <th>CDA Registration No</th>
                        <th>Accreditation No</th>
                        <th>Cooperative Name</th>
                        <th>Validity Date</th>
                        <th>Region</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach ($cooperatives as $coop)
                        <tr>
                            <td>{{ $coop->cda_registration_no }}</td>
                            <td>{{ $coop->accreditation_no }}</td>
                            <td>{{ $coop->name }}</td>
                            <td>{{ \Carbon\Carbon::parse($coop->validity_date)->format('F d, Y') }}</td>
                            <td>{{ $coop->region ?? 'N/A' }}</td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
        @endif

        <div class="user-info">
            <h3>Report Generated By</h3>
            <p>
                <strong>Employee ID No:</strong> {{ $user->employee_id_no }}<br>
                <strong>Name:</strong> {{ $user->firstname }} {{ $user->lastname }}<br>
                <strong>Division:</strong> {{ $user->division }}<br>
                <strong>Role:</strong> {{ $user->role }}<br>
                <strong>Email:</strong> {{ $user->email }}
            </p>
        </div>
    </div>
</body>

</html>
