<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>CGS Renewal Report</title>
    <script src="https://cdn.jsdelivr.net/npm/tailwindcss@2.1.2/dist/tailwind.min.js"></script>
</head>
<body class="bg-gray-50 font-sans">

    <div class="text-center py-6">
        <h2 class="text-3xl font-bold text-gray-800">CGS Renewal Report</h2>
        <p class="text-sm text-gray-600">Generated on: {{ now()->format('F j, Y') }}</p>
    </div>

    <div class="max-w-7xl mx-auto px-6 py-4">
        @if ($cooperatives->isEmpty())
            <div class="text-center text-lg text-red-600">
                <p>No records found</p>
            </div>
        @else
            <table class="min-w-full table-auto bg-white border border-gray-200 rounded-lg shadow-md">
                <thead class="bg-gray-100">
                    <tr>
                        <th class="px-4 py-2 text-left text-sm font-semibold text-gray-700">CDA Registration No</th>
                        <th class="px-4 py-2 text-left text-sm font-semibold text-gray-700">Accreditation No</th>
                        <th class="px-4 py-2 text-left text-sm font-semibold text-gray-700">Cooperative Name</th>
                        <th class="px-4 py-2 text-left text-sm font-semibold text-gray-700">Validity Date</th>
                        <th class="px-4 py-2 text-left text-sm font-semibold text-gray-700">Region</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach ($cooperatives as $coop)
                        <tr class="border-t hover:bg-gray-50">
                            <td class="px-4 py-2 text-sm text-gray-700">{{ $coop->cda_registration_no }}</td>
                            <td class="px-4 py-2 text-sm text-gray-700">{{ $coop->accreditation_no }}</td>
                            <td class="px-4 py-2 text-sm text-gray-700">{{ $coop->name }}</td>
                            <td class="px-4 py-2 text-sm text-gray-700">{{ \Carbon\Carbon::parse($coop->validity_date)->format('F d, Y') }}</td>
                            <td class="px-4 py-2 text-sm text-gray-700">{{ $coop->region ?? 'N/A' }}</td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
        @endif

        <div class="mt-6">
            <h3 class="text-lg font-semibold text-gray-700">Report Generated By</h3>
            <p class="text-sm text-gray-600">
                <strong>Employee ID No:</strong> {{ $user->employee_id_no }}<br>
                <strong>Name:</strong> {{ $user->firstname }} {{ $user->lastname }}<br>
                <strong>Division:</strong> {{ $user->division }}<br>
                <strong>Role:</strong> {{ $user->role }}<br>
                <strong>Email:</strong> {{ $user->email }}
            </p>
        </div>
    </div>

</body>
</html>
