<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Application Report</title>
    <style>
        body {
            font-family: DejaVu Sans, sans-serif;
            font-size: 12px;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 15px;
        }
        th, td {
            border: 1px solid #000;
            padding: 5px;
            text-align: left;
        }
        h2 {
            text-align: center;
        }
    </style>
</head>
<body>
    <h2>{{ strtoupper(str_replace('_', ' ', request('report_type'))) }} REPORT</h2>
    <p>Generated by: {{ $user->name }}</p>
    <p>Date: {{ now()->format('F j, Y') }}</p>

    <table>
        <thead>
            <tr>
                <th>#</th>
                <th>Cooperative Name</th>
                <th>CDA Registration No.</th>
                <th>Registration Date</th>
                <th>Region</th>
                <th>Status</th>
                <th>Submitted On</th>
            </tr>
        </thead>
        <tbody>
            @forelse ($cooperatives as $index => $coop)
                <tr>
                    <td>{{ $index + 1 }}</td>
                    <td>{{ $coop->tc_name }}</td>
                    <td>{{ $coop->cda_reg_no }}</td>
                    <td>{{ $coop->cda_reg_date ? \Carbon\Carbon::parse($coop->cda_reg_date)->format('F j, Y') : 'N/A' }}</td>
                    <td>{{ $coop->region }}</td>
                    <td>{{ ucfirst($coop->status) }}</td>
                    <td>{{ \Carbon\Carbon::parse($coop->created_at)->format('F j, Y') }}</td>
                </tr>
            @empty
                <tr>
                    <td colspan="7" style="text-align: center;">No data available.</td>
                </tr>
            @endforelse
        </tbody>
    </table>
</body>
</html>
