<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <title>Application Report</title>
    <style>
        body {
            font-family: DejaVu Sans, sans-serif;
            font-size: 12px;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 15px;
        }

        th,
        td {
            border: 1px solid #000;
            padding: 5px;
            text-align: left;
        }

        h2 {
            text-align: center;
        }

        .user-info {
            margin-top: 40px;
            padding-top: 20px;
            border-top: 1px solid #e5e7eb;
        }

        .user-info h3 {
            font-size: 16px;
            font-weight: 600;
            color: #374151;
        }

        .user-info p {
            font-size: 14px;
            color: #6b7280;
        }
    </style>
</head>

<body>
    <h2>{{ strtoupper(str_replace('_', ' ', request('report_type'))) }} REPORT</h2>
    <p>Generated by: {{ $user->name }}</p>
    <p>Date: {{ now()->format('F j, Y') }}</p>

    <table>
        <thead>
            <tr>
                <th>#</th>
                <th>Cooperative Name</th>
                <th>CDA Registration No.</th>
                <th>Registration Date</th>
                <th>Region</th>
                <th>Status</th>
                <th>Submitted On</th>
            </tr>
        </thead>
        <tbody>
            @forelse ($cooperatives as $index => $coop)
                <tr>
                    <td>{{ $index + 1 }}</td>
                    <td>{{ $coop->tc_name }}</td>
                    <td>{{ $coop->cda_reg_no }}</td>
                    <td>{{ $coop->cda_reg_date ? \Carbon\Carbon::parse($coop->cda_reg_date)->format('F j, Y') : 'N/A' }}
                    </td>
                    <td>{{ $coop->region }}</td>
                    <td>{{ ucfirst($coop->status) }}</td>
                    <td>{{ \Carbon\Carbon::parse($coop->created_at)->format('F j, Y') }}</td>
                </tr>
            @empty
                <tr>
                    <td colspan="7" style="text-align: center;">No data available.</td>
                </tr>
            @endforelse
        </tbody>
    </table>

    <div class="user-info">
        <h3>Report Generated By</h3>
        <p>
            <strong>Employee ID No:</strong> {{ $user->employee_id_no }}<br>
            <strong>Name:</strong> {{ $user->firstname }} {{ $user->lastname }}<br>
            <strong>Division:</strong> {{ $user->division }}<br>
            <strong>Role:</strong> {{ $user->role }}<br>
            <strong>Email:</strong> {{ $user->email }}
        </p>
    </div>
</body>

</html>
